using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using KVideoLauncher.Data;
using KVideoLauncher.Tools.Converters;

namespace KVideoLauncher.Models;

public class SettingsModel
{
    #region Setting properties generated by KVideoLauncher

    // TODO: Use IDictionary<K,V> instead.
    [JsonConverter(typeof(CaseInsensitiveDictionaryJsonConverter<string>))]
    public Dictionary<string, string> LastEnteredPathByDrive { get; init; } = new(StringComparer.OrdinalIgnoreCase);

    // TODO: Use IDictionary<K,V> instead.
    // TODO: Use `init` accessor instead.
    [JsonConverter(typeof(CaseInsensitiveDictionaryJsonConverter<int>))]
    public Dictionary<string, int> EntryFrequencyByPath { get; set; } = new(StringComparer.OrdinalIgnoreCase);

    #endregion

    #region Setting properties for users to customize

    public IEnumerable<string> VideoFileExtensions { get; init; } =
        new[] { ".AVI", ".FLV", ".MKV", ".MOV", ".MP4", ".RM", ".RMVB", ".TS", ".PS", ".WMV" }.AsReadOnly();

    public IEnumerable<string> SubtitleFileExtensions { get; init; } =
        new[] { ".SRT", ".SUB", ".IDX", ".ASS" }.AsReadOnly();

    public IEnumerable<DirectoryDisplayingInfo> PinnedDirectories { get; init; } =
        Enumerable.Empty<DirectoryDisplayingInfo>();

    #endregion
}