//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVideoLauncher.Properties.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KVideoLauncher.Properties.Lang.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Directories: 的本地化字符串。
        /// </summary>
        public static string Directories {
            get {
                return ResourceManager.GetString("Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drives: 的本地化字符串。
        /// </summary>
        public static string Drives {
            get {
                return ResourceManager.GetString("Drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception 的本地化字符串。
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Files: 的本地化字符串。
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frequent: 的本地化字符串。
        /// </summary>
        public static string Frequent {
            get {
                return ResourceManager.GetString("Frequent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to parent directory 的本地化字符串。
        /// </summary>
        public static string GoToParentDirectory {
            get {
                return ResourceManager.GetString("GoToParentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert all files into current playlist 的本地化字符串。
        /// </summary>
        public static string InsertAllFilesIntoCurrentPlaylist {
            get {
                return ResourceManager.GetString("InsertAllFilesIntoCurrentPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert selected file and the ones above into current playlist 的本地化字符串。
        /// </summary>
        public static string InsertSelectedFileAndAboveIntoCurrentPlaylist {
            get {
                return ResourceManager.GetString("InsertSelectedFileAndAboveIntoCurrentPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert selected file and the ones below into current playlist 的本地化字符串。
        /// </summary>
        public static string InsertSelectedFileAndBelowIntoCurrentPlaylist {
            get {
                return ResourceManager.GetString("InsertSelectedFileAndBelowIntoCurrentPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest playlist 的本地化字符串。
        /// </summary>
        public static string LatestPlaylist {
            get {
                return ResourceManager.GetString("LatestPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please make sure that the play command you have configured in the settings file is correct. 的本地化字符串。
        /// </summary>
        public static string MakeSurePlayCommandIsCorrect {
            get {
                return ResourceManager.GetString("MakeSurePlayCommandIsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move down 的本地化字符串。
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move up 的本地化字符串。
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network 的本地化字符串。
        /// </summary>
        public static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next playlist 的本地化字符串。
        /// </summary>
        public static string NextPlaylist {
            get {
                return ResourceManager.GetString("NextPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There&apos;s nothing to play. 的本地化字符串。
        /// </summary>
        public static string NothingToPlay {
            get {
                return ResourceManager.GetString("NothingToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playlist: 的本地化字符串。
        /// </summary>
        public static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of the files in the current playlist has reached the upper limit. 的本地化字符串。
        /// </summary>
        public static string PlaylistFilesCountHasReachedLimit {
            get {
                return ResourceManager.GetString("PlaylistFilesCountHasReachedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous playlist 的本地化字符串。
        /// </summary>
        public static string PreviousPlaylist {
            get {
                return ResourceManager.GetString("PreviousPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh both directories and files 的本地化字符串。
        /// </summary>
        public static string RefreshBothDirectoriesAndFiles {
            get {
                return ResourceManager.GetString("RefreshBothDirectoriesAndFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target directory doesn&apos;t exist. 的本地化字符串。
        /// </summary>
        public static string TargetDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("TargetDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network... 的本地化字符串。
        /// </summary>
        public static string ToggleNetwork {
            get {
                return ResourceManager.GetString("ToggleNetwork", resourceCulture);
            }
        }
    }
}
